---
version: "2"

checks:
  identical-code:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 75

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3