# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ecves CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/server

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/server/package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Run jest tests and create coverage report
      env: 
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      run: npm run coverage
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        run: cd ./src/server && npm install && npm install ts-node typescript

      - name: Install frontend dependencies
        run: cd ./src/client && npm install

      - name: Run lint
        run: cd ./src/client && npm run lint

      - name: Run Cypress
        uses: cypress-io/github-action@v5

        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}

        with:
          command: npm run cypress:e2e
          start: npm run build:frontend, npm run test:server
          wait-on: 'http://localhost:3001/'
