# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ecves CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/server/package-lock.json
    - name: Install dependencies
      run: cd src/server/ && npm install
    - name: Run lint
      run: cd src/server/ && npm run lint
    - name: Run jest tests and create coverage report
      run: cd src/server/ && npm run coverage
      working-directory: src/server
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)
